version: "3.9"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    ports:
      - 8010:8010
  bot:
    build: .
    container_name: your_grammar_bot
    command: python discord/main.py
    depends_on:
      - languagetool
